The steady state distribution of a transition matrix 𝑃 with dimensionality 𝑁 ×𝑁, is shown by an 𝑁-dimensional row-vector 𝜋. Its value 𝜋𝑖  gives the probability that the user performing the random walk over the web graph is currently at page 𝑖 after performing infinitely many moves. This can also be interpreted as the probability that the user is at page 𝑖 at the current time step if the page the user was at the previous step is unknown. This value is the score of a page following the page-rank algorithm, meaning that 𝜋𝑖 is the page-rank score of page 𝑖.

The vector 𝜋 can be calculated as the left eigenvector for the largest (principal) eigenvalue of the transition matrix 𝑃, using the formula 𝜋=𝜋⋅𝑃. The steady state distribution for a transition matrix 𝑃 is guaranteed to exist if the matrix contains no zero entries, which in turn can be guaranteed with a teleportation rate 𝛼> 0.

If the start vector x0 = (1/3, 1/3, 1/3) and transition matrix is

\begin{bmatrix} 4/15 & 5/15 & 6/15 \\ 1/15 & 13/15 & 1/15\\ 13/15 & 1/15 & 1/15 \\ \end{bmatrix}

In [1]:
import numpy as np
a = np.array([[6/15, 5/15, 4/15], [1/15,1/15,13/15], [1/15,13/15,1/15]])

In [2]:
a = np.matrix(a)
a

matrix([[0.4       , 0.33333333, 0.26666667],
        [0.06666667, 0.06666667, 0.86666667],
        [0.06666667, 0.86666667, 0.06666667]])

In [3]:
x0 = np.matrix([1/3,1/3,1/3])
x0

matrix([[0.33333333, 0.33333333, 0.33333333]])

In [4]:
x0,a

(matrix([[0.33333333, 0.33333333, 0.33333333]]),
 matrix([[0.4       , 0.33333333, 0.26666667],
         [0.06666667, 0.06666667, 0.86666667],
         [0.06666667, 0.86666667, 0.06666667]]))

Calculate the steady state distribution of the given transition matrix using the power iteration method with 5 iterations.

In [8]:
x0*(a**5)

matrix([[0.10096022, 0.45425558, 0.4447842 ]])

In [9]:
a0 = x0*a**0
a1 = x0*a**1
a2 = x0*a**2
a3 = x0*a**3
a4 = x0*a**4
a5 = x0*a**5
a6 = x0*a**6
a7 = x0*a**7
a8 = x0*a**8
a9 = x0*a**9
a10 = x0*a**10
a11 = x0*a**11
a12 = x0*a**12
a13 = x0*a**13
a14 = x0*a**14
a15 = x0*a**15

In [14]:
#Convergence with iteration
print("2",a2-a1,a2-a1 <= [0.001,0.001,0.001])
print("3",a3-a2,a3-a2 <= [0.001,0.001,0.001])
print("4",a4-a3,a4-a3 <= [0.001,0.001,0.001])
print("5",a5-a4,a5-a4 <= [0.001,0.001,0.001])
print("6",a6-a5,a6-a5 <= [0.001,0.001,0.001])
print("7",a7-a6,a7-a6 <= [0.001,0.001,0.001])
print("8",a8-a7,a8-a7 <= [0.001,0.001,0.001])
print("9",a9-a8,a9-a8 <= [0.001,0.001,0.001])
print("10",a10-a9,a10-a9 <= [0.001,0.001,0.001])
print("11",a11-a10,a11-a10 <= [0.001,0.001,0.001])
print("12",a12-a11,a12-a11 <= [0.001,0.001,0.001])
print("13",a13-a12,a13-a12 <= [0.001,0.001,0.001])
print("14",a14-a13,a14-a13 <= [0.001,0.001,0.001])
print("15",a15-a14,a15-a14 <= [0.001,0.001,0.001])

2 [[-0.05185185  0.01185185  0.04      ]] [[ True False False]]
3 [[-0.01728395  0.01817284 -0.00088889]] [[ True False  True]]
4 [[-0.00576132 -0.00532016  0.01108148]] [[ True  True False]]
5 [[-0.00192044  0.00732883 -0.0054084 ]] [[ True False  True]]
6 [[-0.00064015 -0.00483883  0.00547898]] [[ True  True False]]
7 [[-0.00021338  0.00421248 -0.0039991 ]] [[ True False  True]]
8 [[-7.11273688e-05 -3.25617849e-03  3.32730586e-03]] [[ True  True False]]
9 [[-2.37091229e-05  2.64287739e-03 -2.61916827e-03]] [[ True False  True]]
10 [[-7.90304098e-06 -2.10165705e-03  2.10956009e-03]] [[ True  True False]]
11 [[-2.63434699e-06  1.68554059e-03 -1.68290625e-03]] [[ True False  True]]
12 [[-8.78115664e-07 -1.34702749e-03  1.34790561e-03]] [[ True  True False]]
13 [[-2.92705221e-07  1.07809032e-03 -1.07779761e-03]] [[ True False  True]]
14 [[-9.75684071e-08 -8.62316146e-04  8.62413715e-04]] [[ True  True  True]]
15 [[-3.25228024e-08  6.89904954e-04 -6.89872431e-04]] [[ True  True  True]]
