In [1]:
print("Hello world")

Hello world


In [2]:
print("Hello \n world")

Hello 
 world


In [4]:
print("Hello \" world")

Hello " world


In [7]:
word = "Prajna Shetty"
print(word.lower())
print(word.upper())
print(word.islower())
print(word.isupper())

prajna shetty
PRAJNA SHETTY
False
False


In [30]:
print(len(word))

13


In [31]:
print("word " + word[0])

word P


In [12]:
print(word.index("S"))

7


In [13]:
print(word.replace("Prajna","Pratheek"))

Pratheek Shetty


In [14]:
num = 3
print(str(num))

3


In [15]:
dig = -7
print(abs(dig))

7


In [17]:
print(pow(dig,2))

49


In [18]:
print(max(dig,num))
print(min(dig,num))

3
-7


In [19]:
print(round(3.7))

4


In [22]:
from math import *

print(floor(3.7))
print(ceil(3.7))
print(sqrt(3.7))

3
4
1.9235384061671346


In [24]:
name = input("Enter your name: ")
print(name)

Enter your name: Sai
Sai


In [26]:
a = input("Enter a number ")
b = input("Enter a number ")
print(int(a)+int(b))

Enter a number 1
Enter a number 2
3


In [27]:
a = input("Enter a number ")
b = input("Enter a number ")
print(float(a)+float(b))

Enter a number 3.9
Enter a number 9.0
12.9


In [52]:
peep = ["abc","lmh","ghi","yuo"]
print(peep[1:3])

['lmh', 'ghi']


In [33]:
print(peep[1:])

['def', 'ghi', 'jkl']


In [34]:
print(peep[:3])

['abc', 'def', 'ghi']


In [39]:
nums = [1,2,3]
peep.extend(nums)
print(peep)

['abc', 'def', 'ghi', 'jkl', 1, 2, 3]


In [43]:
peep.append("mno")
print(peep)

['abc', 'def', 'ghi', 'jkl', 'mno']


In [44]:
peep.insert(1, "new")
print(peep)

['abc', 'new', 'def', 'ghi', 'jkl', 'mno']


In [45]:
peep.remove("mno")
print(peep)

['abc', 'new', 'def', 'ghi', 'jkl']


In [46]:
peep.pop()
print(peep)

['abc', 'new', 'def', 'ghi']


In [47]:
peep.clear()
print(peep)

[]


In [50]:
print(peep.index("abc"))

0


In [51]:
print(peep.count("abc"))

1


In [53]:
peep.sort()
print(peep)

['abc', 'ghi', 'lmh', 'yuo']


In [54]:
peep.reverse()
print(peep)

['yuo', 'lmh', 'ghi', 'abc']


In [55]:
peep2 = peep.copy()
print(peep2)

['yuo', 'lmh', 'ghi', 'abc']


In [56]:
tuple = ["abc","lmh","ghi","yuo"]
print(tuple)

['abc', 'lmh', 'ghi', 'yuo']


In [59]:
tuplelist = [("abc","lmh"),("ghi","yuo")]
print(tuplelist)

[('abc', 'lmh'), ('ghi', 'yuo')]


In [61]:
def first_function():
    print("Hi")
first_function()

Hi


In [71]:
if 1<2 or 2>1:
    print("Always")
elif 1<3 and not(3>1):
    print("Never")
else:
    print("no")

Always


In [72]:
dictonaries = {
    "jan": "1",
    "feb": "2",
    "mar": "3",
}
print(dictonaries)

{'jan': '1', 'feb': '2', 'mar': '3'}


In [74]:
print(dictonaries["feb"])

2


In [75]:
print(dictonaries.get("feb"))

2


In [76]:
print(dictonaries.get("Apr"))

None


In [78]:
print(dictonaries.get("Apr", "Not present"))

Not present


In [1]:
for name in "Prajna Shetty":
    print(name)

P
r
a
j
n
a
 
S
h
e
t
t
y


In [3]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [4]:
for i in range(len("PrajnaShetty")):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [6]:
try:
    num = int(input("Enter the number: "))
    print(num)
except:
    print("Exception occured")

Enter the number: iop
Exception occured


In [11]:
try:
    num = int(input("Enter the number: "))
    print(2/num)
except ZeroDivisionError:
    print("Cant divide by zero")
except ValueError:
    print("Invalid value")

Enter the number: 0
Cant divide by zero


In [36]:
#Reading files
file = open("cinderella.txt", "r")
print(file.readable())
print(file.read())
file.close()

True
new line


In [35]:
#Writing to files
file = open("cinderella.txt", "w")
print(file.readable())
file.write("new line")
file.close()

False


In [20]:
#Appending files
file = open("cinderella.txt", "a")
print(file.readable())
file.close()

False


In [26]:
#Reading and Writing files
file = open("cinderella.txt", "r+")
print(file.readable())
print(file.readline())
file.close()

True
uiiui



In [27]:
#Puts in a List
file = open("cinderella.txt", "r")
print(file.readlines())
file.close()

['uiiui\n', 'ioiop\n', 'oippop[o\n', 'nljbkjb\n', '\n', '\n', 'kjjhb\n', 'nmmmmmmmmmmmmjbjnm ']


In [33]:
file = open("cinderella.txt", "r")
print(file.readlines()[1])

ioiop



In [34]:
for j in file.readlines():
    print(j)

In [37]:
import numpy as np

a  = np.array([1,2,3])
print(a)

[1 2 3]


In [92]:
b  = np.array([[1,2,3], [3,4,5]])
print(b)

[[1 2 3]
 [3 4 5]]


In [41]:
a.ndim

1

In [42]:
b.ndim

2

In [43]:
a.shape

(3,)

In [44]:
b.shape

(2, 3)

In [45]:
a.dtype

dtype('int32')

In [93]:
c  = np.array([[1,2,3], [3,4,5]], dtype='int16')
c.dtype

dtype('int16')

In [47]:
a.itemsize

4

In [48]:
c.itemsize

2

In [49]:
a.size

3

In [50]:
a.nbytes

12

In [52]:
c.nbytes

12

In [53]:
x= np.array([[1,2,3,4],[3,5,6,7],[6,2,3,5]])
x[1:5]

array([[3, 5, 6, 7],
       [6, 2, 3, 5]])

In [55]:
x[:3]

array([[1, 2, 3, 4],
       [3, 5, 6, 7],
       [6, 2, 3, 5]])

In [60]:
x[2:]

array([[6, 2, 3, 5]])

In [61]:
x[0, :]

array([1, 2, 3, 4])

In [63]:
x[: , 2]

array([3, 6, 3])

In [65]:
#Skip by 2 from 1-3th col 0 row
x[0,1:3:2]

array([2])

In [66]:
x[1,3] = 100
x

array([[  1,   2,   3,   4],
       [  3,   5,   6, 100],
       [  6,   2,   3,   5]])

In [67]:
y = np.array([[[1,2,3,4],[3,5,6,7],[6,2,3,5]],[[1,2,3,4],[3,5,6,7],[6,2,3,5]]])
y

array([[[1, 2, 3, 4],
        [3, 5, 6, 7],
        [6, 2, 3, 5]],

       [[1, 2, 3, 4],
        [3, 5, 6, 7],
        [6, 2, 3, 5]]])

In [69]:
y[:,1,:] = [[5,5,5,5],[6,6,6,6]]
y

array([[[1, 2, 3, 4],
        [5, 5, 5, 5],
        [6, 2, 3, 5]],

       [[1, 2, 3, 4],
        [6, 6, 6, 6],
        [6, 2, 3, 5]]])

In [70]:
y[:,2,:]

array([[6, 2, 3, 5],
       [6, 2, 3, 5]])

In [71]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [73]:
np.zeros(((2,3,2)))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [74]:
np.ones((2,3,2), dtype='int32')

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [75]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [76]:
np.full_like(y,4)

array([[[4, 4, 4, 4],
        [4, 4, 4, 4],
        [4, 4, 4, 4]],

       [[4, 4, 4, 4],
        [4, 4, 4, 4],
        [4, 4, 4, 4]]])

In [78]:
np.random.rand(4,2,3)

array([[[0.59464779, 0.66558055, 0.99493082],
        [0.19439909, 0.45934154, 0.60439465]],

       [[0.43642857, 0.04569863, 0.87243586],
        [0.70698631, 0.7771461 , 0.97506303]],

       [[0.45153203, 0.37180311, 0.04171573],
        [0.80519819, 0.73697785, 0.0953708 ]],

       [[0.41907435, 0.46228584, 0.1285454 ],
        [0.4633853 , 0.95595397, 0.55575657]]])

In [81]:
o = np.ones((5,5))
o[1:-1,1:-1] = 0
o

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [86]:
b = a.copy()
b

array([1, 2, 3])

In [88]:
b*2

array([2, 4, 6])

In [89]:
a+b

array([2, 4, 6])

In [90]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [101]:
c  = np.array([[1,2], [3,4],[6,7]])
np.matmul(b,c)

array([[25, 31],
       [45, 57]])

In [ ]:
#Load data from file
filedata = np.genfromtxt('data.txt',delimiters=',')
filedata[filedata>50 ]

In [ ]:
import pandas as pd